apply plugin: 'com.android.library'

android {
    namespace "org.vosk.models"
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
    }
    buildFeatures {
        buildConfig = false
    }
    sourceSets {
        main {
            assets.srcDirs += "$buildDir/generated/assets"
        }
    }
}

tasks.register('genUUIDs') {
    def modelsDir = file("src/main/assets")

    doLast {
        modelsDir.eachDir { modelDir ->
            def modelName = modelDir.name
            def uuid = UUID.randomUUID().toString()
            def odir = file("$buildDir/generated/assets/$modelName")
            def ofile = file("$odir/uuid")

            mkdir odir
            ofile.text = uuid
            println "Generated UUID for model $modelName: $uuid"
        }
    }
}

preBuild.dependsOn(genUUIDs)